### ISSUE TITLE
Could you post somewhere the weights of the wining tickets for each model/dataset?

### ISSUE THREAD

**Issue by kirk86** [rahulvigneswaran/Lottery-Ticket-Hypothesis-in-Pytorch#4]
Hi, thanks for reproducible effort.
I was wondering if you could post somewhere (i.e. google drive, dropbox, etc.) the wining ticket for each model and dataset?

**Comment by rahulvigneswaran** [comment]
@kirk86 I am sorry. I have deleted them long back.
